Region: us-east-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-081031c727748fcc3
  Ssh:
    KeyName: AWS-Keys
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute-queue
      ComputeResources:
        - Name: compute
          InstanceType: t3.medium
          MinCount: 1
          MaxCount: 2
      Networking:
        SubnetIds:
          - subnet-081031c727748fcc3
# SharedStorage:
#   - MountDir: /shared
#     Name: efs-storage
#     StorageType: Efs
Tags:
  - Key: Project
    Value: fineweb-data
  - Key: Environment
    Value: development
